### ISSUE TITLE
Missing Edge Type

### ISSUE THREAD

**Issue by ronakice** [caoyu1991/BAG#3]
Hi! 

Did you conduct any studies on using the exact edges defined in Cao's Question answering by reasoning across documents with graph convolutional networks. It seems like you are missing one edge-type? (Also, coreference resolved nodes) Any reason why?

Thanks,
Ronak

**Comment by caoyu-noob** [comment]
Hi, thanks for your question. Our model is based on their early version and no coreference edges are included at that time. We did not test our model with new edge type yet, and maybe we will do it later.
